# Header Menu
menu:
  Home: /
  # Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  # Contact: /contact/
  About: /about/

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname:
google_analytics:
swiftype_install_key:

# Social
social:
  github: https://github.com/adu-21
  twitter: https://twitter.com/duuyidong
  facebook: https://www.facebook.com/luke.du.16
  rss: atom.xml
  linkedin: https://linkedin.com/in/yidong-du-0868b0123
  stackoverflow: http://stackoverflow.com/users/6069208/luke-du

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_username: duuyidong # twitter username without the @
default_author: Anonymous

about: Yidong is a software developer working on ThoughtWorks based in Chengdu, China. <br><br> Focus on Cloud, DevOps, good at Java & Python development.
phone: +86 182-0282-2793
wechat: duuyidong
email: duuyidong@gmail.com
address_1: Chengdu, Sichuan
address_2: China
skype: Yidong Du
lat: 40.715911
long: -73.962147
